org: lucaslima7
app: socio-bebedor-service-app
service: socio-bebedor-service
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
functions:
  getTeams:
    handler: src/index.handler
    events:
      - http:
          path: teams
          method: get
  getTeamsCount:
    handler: src/index.handler
    events:
      - http:
          path: teams/count
          method: get
  getTeamById:
    handler: src/index.handler
    events:
      - http:
          path: teams/{id}
          method: get
  deleteTeamById:
    handler: src/index.handler
    events:
      - http:
          path: teams/{id}
          method: delete
  createTeam:
    handler: src/index.handler
    events:
      - http: 
          path: teams
          method: post
  updateTeam:
    handler: src/index.handler
    events:
      - http:
          path: teams/{id}
          method: put
plugins:
  - serverless-plugin-typescript
  - serverless-offline