org: lucaslima7
app: socio-bebedor-service-app
service: socio-bebedor-service

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: sa-east-1
  memorySize: 512

functions:
  teamsFunc:
    handler: index.handler
    events:
      - http:
          path: teams
          method: get
      - http:
          path: teams/count
          method: get
      - http:
          path: teams/{id}
          method: get
      - http:
          path: teams
          method: post
      - http:
          path: teams/{id}
          method: put
      - http:
          path: teams/{id}
          method: delete

plugins:
  - serverless-plugin-typescript
  - serverless-offline